const Menu =[{
    id:1,
    image:"images/penne-pasta.jpg",
    name:"Chowmain",
    category:"Dinner",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
{
    id:2,
    image:"images/fried-chicken.jpg",
    name:"Shakes",
    category:"Breakfast",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
{
    id:3,
    image:"images/fried-chicken.jpg",
    name:"kabab",
    category:"lunch",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
{
    id:4,
    image:"images/penne-pasta.jpg",
    name:"penny-pasta",
    category:"lunch",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
{
    id:5,
    image:"images/fried-chicken.jpg",
    name:"platter",
    category:"Dinner",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
{
    id:6,
    image:"images/penne-pasta.jpg",
    name:"omlette",
    category:"Breakfast",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
{
    id:7,
    image:"images/fried-chicken.jpg",
    name:"Biryani",
    category:"Dinner",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
{
    id:8,
    image:"images/fried-chicken.jpg",
    name:"Burger",
    category:"lunch",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
{
    id:9,
    image:"images/penne-pasta.jpg",
    name:"Fries",
    category:"lunch",
    price:"120rs",
    description:"love this penney made with tomato souce",
},
];

export default Menu;